--GROUP BY 중복 출력
SELECT A.AGRDE_SE_CD
     , SUM(A.POPLTN_CNT) AS POPLTN_CNT
  FROM TB_POPLTN A
 WHERE A.STD_YM = '202010'
   AND A.POPLTN_SE_CD = 'T'
 GROUP BY ROLLUP(A.AGRDE_SE_CD), A.AGRDE_SE_CD
 ORDER BY A.AGRDE_SE_CD;

-- NULL 값 MAX함수로 강제 표시
SELECT NVL(MAX(STATN_NM), '역명없음') AS STATN_NM
  FROM TB_SUBWAY_STATN
 WHERE STATN_NM = '평양역'
;

SELECT CASE WHEN COUNT(*) = 0 THEN '역명없음'
            ELSE MAX(STATN_NM) END AS STATN_NM
  FROM TB_SUBWAY_STATN
 WHERE STATN_NM = '평양역'
;

--집계 함수를 이용하지 않은 컬럼은 반드시 GROUP BY 절에 기재
SELECT POPLTN_SE_CD
     , MAX(POPLTN_CNT) POPLTN_CNT
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD
 ;