--DBEAVER에서 CTRL+SHIFT+E를 누르면 실행계획이 출력됨
SELECT A.ADSTRD_CD
     , A.STD_YM
     , A.POPLTN_SE_CD
     , A.AGRDE_SE_CD
     , A.POPLTN_CNT
     , B.ADSTRD_NM
  FROM TB_POPLTN A
     , TB_ADSTRD B
 WHERE A.ADSTRD_CD = B.ADSTRD_CD
   AND A.ADSTRD_CD = '1154551000'
;

--통계레벨 설정: 현재 접속되어 있는 세션의 통계레벨을 ALL로 설정
--지금부터 실행되는 SQL문이 실제로 어떤 동작을 했는지 추적하게 됨
ALTER SESSION SET STATISTICS_LEVEL = ALL;

SELECT /* SELECT.TB_POPLTN.TB_ADSTRD.001 */
       A.ADSTRD_CD 
     , A.STD_YM
     , A.POPLTN_SE_CD
     , A.AGRDE_SE_CD
     , A.POPLTN_CNT
     , B.ADSTRD_NM
  FROM TB_POPLTN A
     , TB_ADSTRD B
 WHERE A.ADSTRD_CD = B.ADSTRD_CD
   AND A.ADSTRD_CD = '1154551000'
;

--SQL문의 실행 정보 조회
SELECT
       SQL_ID
     , CHILD_NUMBER
     , SUBSTR(SQL_FULLTEXT,1,40)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_POPLTN.TB_ADSTRD.001%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
;

--실행내역 출력
SELECT *
  FROM TABLE
       (DBMS_XPLAN.DISPLAY_CURSOR ('63aqvb7433jm9',1,'ALLSTATS LAST -ROWS'))
;