--7.2.12 인덱스 스킵 스캔
--7-22 인덱스 생성
CREATE INDEX IDX_TB_SUB_STA_TK_GFF_TMP_03 ON TB_SUBWAY_STATN_TK_GFF_TMP
(TK_GFF_SE_CD, SUBWAY_STATN_NO);


--7-23 통계정보 생성
ANALYZE INDEX idx_tb_sub_sta_tk_gff_tmp_03 estimate STATISTICS;

--7-24 통계레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

--7-25 인덱스 스킵 스캔 유도
SELECT /*+ INDEX_SS(A IDX_TB_SUB_STA_TK_GFF_TMP_03) */
/* SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.004 */
       A.SUBWAY_STATN_NO
     , A.STD_YM 
     , A.BEGIN_TIME 
     , A.END_TIME 
     , A.TK_GFF_SE_CD 
     , A.TK_GFF_CNT 
  FROM TB_SUBWAY_STATN_TK_GFF_TMP A
 WHERE A.SUBWAY_STATN_NO = '000376'
 ;

 --7-10 SQL 실행 정보 조회
 SELECT SQL_ID
      , CHILD_NUMBER
      , SUBSTR(SQL_FULLTEXT, 1, 60)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.INDEX_SS(A IDX_TB_SUB_STA_TK_GFF_TMP_03)%'
   AND SQL_FULLTEXT NOT LIKE '$V$SQL%'
 ORDER BY LAST_ACTIVE_TIME DESC
;

--7-11 실행내역 확인
SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('a5dzg2r7ja8jg', 0 ,'ALLSTATS LAST -ROWS'))
;