-- 7.2.13 인덱스 고속 풀 스캔
-- 7-26 인덱스 생성
CREATE INDEX IDX_TB_SUB_STA_TK_GFF_TMP_04
  ON TB_SUBWAY_STATN_TK_GFF_TMP(STD_YM, BEGIN_TIME, END_TIME);
  
-- 7-27 통계정보 생성
ANALYZE INDEX IDX_TB_SUB_STA_TK_GFF_TMP_04 ESTIMATE STATISTICS;

-- 7-28 통계레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

-- 7-29 SQL문 실행
SELECT /*+ INDEX_FSS(A IDX_TB_SUB_STA_TK_GFF_TMP_04) */
       /* SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.005 */
       A.STD_YM
     , MAX(A.BEGIN_TIME) AS BEGIN_TIME
     , MAX(A.END_TIME) AS END_TIME
  FROM TB_SUBWAY_STATN_TK_GFF_TMP A
 WHERE A.STD_YM >= '00000000'
 GROUP BY A.STD_YM
;

-- 7-10 SQL 실행 정보 조회
SELECT
       SQL_ID
     , CHILD_NUMBER
     , SUBSTR(SQL_FULLTEXT, 1, 60)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.005%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
 ORDER BY LAST_ACTIVE_TIME DESC
;

-- 7-11 실행내역 확인
SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('c5zxhg66mzdjf',0,'ALLSTATS LAST -ROWS'))
;