-- 7.2.10 인덱스 유일 스캔
-- 7-12 지하철역 승하차_임시 테이블 생성
CREATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP AS
SELECT * FROM TB_SUBWAY_STATN_TK_GFF
;

-- 7-13 테이블 통계정보 수집
ANALYZE TABLE TB_SUBWAY_STATN_TK_GFF_TMP COMPUTE STATISTICS;

--7-14 지하철역승하차임시 테이블에 기본키 생성
ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP 
ADD CONSTRAINT PK_TB_SUBWAY_STATN_TK_GFF_TMP
PRIMARY KEY(SUBWAY_STATN_NO,STD_YM,BEGIN_TIME,END_TIME,TK_GFF_SE_CD)
;

--7-15 기본키에 대한 통계정보 수집
ANALYZE INDEX PK_TB_SUBWAY_STATN_TK_GFF_TMP ESTIMATE STATISTICS;

--7-16 통계 레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

--7-17 SQL문 실행
SELECT /* SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.001 */
       A.SUBWAY_STATN_NO 
     , A.STD_YM
     , A.BEGIN_TIME
     , A.END_TIME 
     , A.TK_GFF_SE_CD 
     , A.TK_GFF_CNT 
  FROM TB_SUBWAY_STATN_TK_GFF_TMP A
 WHERE A.SUBWAY_STATN_NO = '000376' --일산선 삼송역
   AND A.STD_YM = '202010'
   AND A.BEGIN_TIME = '0700'
   AND A.END_TIME = '0800'
   AND A.TK_GFF_SE_CD = 'TGS001'
   ;