ALTER SESSION SET statistics_level = ALL;

SELECT /* SELECT.TB_POPLTN.TB_ADSTRD.001 */
       A.ADSTRD_CD
     , A.STD_YM
     , A.POPLTN_SE_CD
     , A.AGRDE_SE_CD
     , A.POPLTN_CNT
     , B.ADSTRD_NM
  FROM TB_POPLTN A
     , TB_ADSTRD B
 WHERE A.ADSTRD_CD = B.ADSTRD_CD
   AND A.ADSTRD_CD = '1154551000'
;
SELECT
       SQL_ID
     , CHILD_NUMBER
     , SUBSTR(SQL_FULLTEXT, 1, 40)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_POPLTN.TB_ADSTRD.001%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
;

SELECT *
  FROM TABLE
    (DBMS_XPLAN.DISPLAY_CURSOR
      ('33h00ffyrpz2n',0,'ALLSTATS LAST -ROWS')
    );