-- 7.2.14 인덱스 역순 범위 스캔
-- 7-30 인덱스 생성
CREATE INDEX IDX_TB_SUB_STA_TK_GFF_TMP_05 ON TB_SUBWAY_STATN_TK_GFF_TMP(STD_YM, END_TIME);

-- 7-32 통계레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

-- 7-33 SQL문 실행
SELECT /*+ INDEX_DESC(A IDX_TB_SUB_STA_TK_GFF_TMP_05) */
       /* SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.006 */
       A.SUBWAY_STATN_NO
     , A.STD_YM 
     , A.BEGIN_TIME 
     , A.END_TIME 
     , A.TK_GFF_SE_CD 
     , A.TK_GFF_CNT 
  FROM TB_SUBWAY_STATN_TK_GFF_TMP A
 WHERE A.STD_YM = '202010'
 AND A.END_TIME <= '1800'
 ORDER BY A.STD_YM, END_TIME DESC 
 ;
 
 -- 7-10 SQL 실행 정보 조회
 SELECT 
        SQL_ID 
      , CHILD_NUMBER 
      , SUBSTR(SQL_FULLTEXT, 1, 60)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_SUBWAY_STATN_TK_GFF_TMP.006%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
 ORDER BY LAST_ACTIVE_TIME DESC 
;

-- 7-11 실행내역 확인
SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('07bd9kh03j31d',0,'ALLSTATS LAST -ROWS'))
;