--7-34 통계레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

--7-35 NL조인
SELECT /*+ LEADING(A) USE_NL(B) */
       /* SELECT.TB_SUBWAY_STATN.TB_SUBWAY_STATN_TK_GFF.001 */
       A.SUBWAY_STATN_NO 
     , A.LN_NM 
     , A.STATN_NM 
     , B.STD_YM 
     , B.BEGIN_TIME 
     , B.END_TIME 
     , B.TK_GFF_SE_CD 
     , B.TK_GFF_CNT 
  FROM TB_SUBWAY_STATN A
     , TB_SUBWAY_STATN_TK_GFF B
 WHERE A.SUBWAY_STATN_NO = '000376' --삼송역
   AND A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO 
 ORDER BY B.STD_YM 
        , B.BEGIN_TIME 
        , B.END_TIME 
        , B.TK_GFF_SE_CD 
;

--7-10 SQL 실행정보 조회
SELECT SQL_ID 
     , CHILD_NUMBER 
     , SUBSTR(SQL_FULLTEXT, 1, 60)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_SUBWAY_STATN.TB_SUBWAY_STATN_TK_GFF.001%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
 ORDER BY LAST_ACTIVE_TIME DESC
;

--7-11 실행내역 확인
SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('4n3hysy8dda75', 0, 'ALLSTATS LAST -ROWS'))
;