--7-38 통계 레벨 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

--7-39 해시 조인
SELECT /*+ LEADING(A) USE_HASH(B) */
       /* SELECT.TB_SUBWAY_STATN.TB_SUBWAY_STATN_TK_GFF.003 */
       A.SUBWAY_STATN_NO
     , A.LN_NM 
     , A.STATN_NM 
     , B.STD_YM 
     , B.BEGIN_TIME 
     , B.END_TIME 
     , B.TK_GFF_SE_CD 
     , B.TK_GFF_CNT 
  FROM TB_SUBWAY_STATN A
     , TB_SUBWAY_STATN_TK_GFF B
 WHERE A.SUBWAY_STATN_NO  = '000376' --삼송역
   AND A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO
 ORDER BY B.STD_YM 
        , B.BEGIN_TIME 
        , B.END_TIME 
        , B.TK_GFF_SE_CD 
;

--7-3 SQL문 실행 정보 조회
SELECT SQL_ID 
     , CHILD_NUMBER
     , SUBSTR(SQL_FULLTEXT, 1, 40)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_SUBWAY_STATN.TB_SUBWAY_STATN_TK_GFF.003%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
;

--실행내역 출력
SELECT *
  FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('8kjsr4cm64qap', 0, 'ALLSTATS LAST -ROWS'));