--7.2.8 인덱스 스캔 실습 준비
-- 테이블 복제
CREATE TABLE TB_BSSH_TMP AS SELECT * FROM TB_BSSH;

-- 테이블 통계정보 수집
ANALYZE TABLE TB_BSSH_TMP COMPUTE STATISTICS;

--인덱스 생성(행정동 코드 칼럼)
CREATE INDEX IDX_TB_BSSH_TMP_01 ON TB_BSSH_TMP(ADSTRD_CD);

--인덱스 통계정보 생성
ANALYZE INDEX IDX_TB_BSSH_TMP_01 ESTIMATE STATISTICS;

--통계레벨 ALL로 설정
ALTER SESSION SET STATISTICS_LEVEL = ALL;

--SQL 실행
SELECT /*SELECT.TB_BSSH_TMP.001 */
       A.BSSH_NO
     , A.CMPNM_NM
     , A.INDUTY_SMALL_CL_CD
     , A.ADSTRD_CD
     , A.LNM_ADRES
     , A.NW_ZIP
     , A.LO
     , A.LA
  FROM TB_BSSH_TMP A
 WHERE A.ADSTRD_CD = '4128157000' --경기도 고양시 덕양구 삼송동
 ORDER BY A.ADSTRD_CD
;

--실행 정보 조회
SELECT 
       SQL_ID
     , CHILD_NUMBER
     , SUBSTR(SQL_FULLTEXT, 1, 60)
  FROM V$SQL
 WHERE SQL_FULLTEXT LIKE '%SELECT.TB_BSSH_TMP.001%'
   AND SQL_FULLTEXT NOT LIKE '%V$SQL%'
 ORDER BY LAST_ACTIVE_TIME DESC
;

--실행내역 확인
SELECT *
  FROM TABLE
      (DBMS_XPLAN.DISPLAY_CURSOR
        ('2a8mvgrhtsfpb',0,'ALLSTATS LAST -ROWS')
      )
;