--8.1 SELECT문
--NOTE_FROM절에서 테이블 앨리어스를 지정할 때 AS를 사용하지 못한다.
SELECT A.SUBWAY_STATN_NO AS "지하철역번호"
     , A.LN_NM AS "노선명"
     , A.STATN_NM AS "역명"
  FROM TB_SUBWAY_STATN A
--  FROM TB_SUBWAY_STATN AS A --에러 발생
 WHERE A.STATN_NM = '강남'
 ;
 
--NOTE_비교 연산 시 비교 칼럼의 값이 NULL인 행은 결과집합에서 제외된다.
--8-3 NULL 허용 칼럼 출력
SELECT INDUTY_CL_CD
     , INDUTY_CL_NM 
     , INDUTY_CL_SE_CD 
     , NVL(UPPER_INDUTY_CL_CD, '[NULL]') AS UPPER_INDUTY_CL_CD
  FROM TB_INDUTY_CL
 WHERE INDUTY_CL_CD LIKE 'O%' --숙박
 ORDER BY INDUTY_CL_SE_CD, INDUTY_CL_CD
;

--8-4 NULL 허용 칼럼은 LIKE 연산에서 비교 불가
SELECT INDUTY_CL_CD
     , INDUTY_CL_NM 
     , INDUTY_CL_SE_CD 
     , UPPER_INDUTY_CL_CD
  FROM TB_INDUTY_CL
 WHERE UPPER_INDUTY_CL_CD LIKE 'O%' --숙박
 ORDER BY INDUTY_CL_SE_CD, INDUTY_CL_CD
;

--8-6 주문 임시 테이블 생성
CREATE TABLE TB_ORD_8_1_2
(
  ORD_NO CHAR(10)
, ORD_DE CHAR(8) NULL
, PRDT_CD CHAR(6) NOT NULL
, CUST_ID VARCHAR2(20) NOT NULL
, CONSTRAINT PK_TB_ORD_8_1_2 PRIMARY KEY(ORD_NO)
)
;

--8-7 주문 임시 테이블에 데이터 입력
INSERT INTO TB_ORD_8_1_2 
  VALUES('1000000001','20210101','P00001','DBMSEXPERT');
INSERT INTO TB_ORD_8_1_2 
  VALUES('1000000002','20210131','P00001','DBMSEXPERT');
INSERT INTO TB_ORD_8_1_2 
  VALUES('1000000003',NULL,'P00001','DBMSEXPERT');
  
--8-8 주문내역 조회
SELECT *
  FROM TB_ORD_8_1_2 
 WHERE ORD_DE BETWEEN '20210101' AND '20210131'
; -- 주문일자가 NULL인 행은 결과집합에서 제외

--8-9 주문일자 칼럼의 값이 NULL인 행까지 출력
SELECT ORD_NO
     , NVL(ORD_DE,'[NULL]') AS ORD_DE
     , PRDT_CD
     , CUST_ID
  FROM TB_ORD_8_1_2 
 WHERE (ORD_DE BETWEEN '20210101' AND '20210131' OR ORD_DE IS NULL)
 ;
 
 --NOTE_ORDER BY 절에 테이블 내의 칼럼명을 기재하면 컬럼값을 기준으로 정렬하고
 --컬럼 앨리어스를 기재하면 컬럼 앨리어서의 값을 가지고 정렬한다.
 --8-10 ORDER BY 절에 테이블 앨리어스 및 컬럼명 기재
SELECT A.SUBWAY_STATN_NO
     , A.BEGIN_TIME
     , (SELECT L.TK_GFF_SE_NM
          FROM TB_TK_GFF_SE L
         WHERE L.TK_GFF_SE_CD = A.TK_GFF_SE_CD) AS TK_GFF_SE_NM
     , TO_CHAR(A.TK_GFF_CNT) "승하차인원수"
  FROM TB_SUBWAY_STATN_TK_GFF A
 WHERE A.STD_YM = '202010'
   AND A.BEGIN_TIME = '0800'
   AND A.END_TIME = '0900'
   AND A.SUBWAY_STATN_NO = '000032' --2호선 강남
 ORDER BY A.TK_GFF_CNT DESC
;

 --8-11 ORDER BY 절에 SELECT절의 컬럼 앨리어스 기재
SELECT A.SUBWAY_STATN_NO
     , A.BEGIN_TIME
     , (SELECT L.TK_GFF_SE_NM
          FROM TB_TK_GFF_SE L
         WHERE L.TK_GFF_SE_CD = A.TK_GFF_SE_CD) AS TK_GFF_SE_NM
     , TO_CHAR(A.TK_GFF_CNT) "승하차인원수"
  FROM TB_SUBWAY_STATN_TK_GFF A
 WHERE A.STD_YM = '202010'
   AND A.BEGIN_TIME = '0800'
   AND A.END_TIME = '0900'
   AND A.SUBWAY_STATN_NO = '000032' --2호선 강남
 ORDER BY "승하차인원수" DESC
;