--8.3 GROUP BY절

--GROUP BY와 HAVING의 위치는 서로 바뀔 수 있다.
--8-18 GROUP BY + HAVING 절
SELECT POPLTN_SE_CD 
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD
HAVING POPLTN_SE_CD IN ('M','F')
 ORDER BY POPLTN_CNT_SUM DESC 
;

--8-19 HAVING + GROUP BY 절
SELECT POPLTN_SE_CD 
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
HAVING POPLTN_SE_CD IN ('M','F')
 GROUP BY POPLTN_SE_CD
 ORDER BY POPLTN_CNT_SUM DESC 
;

--HAVING 없는 GROUP BY 절은 사용 가능하지만 GROUP BY 가 없는 HAVING은 SQL 에러가 발생
--8-20 GROUP BY 없이 HAVING만을 사용한 SQL문
SELECT POPLTN_SE_CD 
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
HAVING POPLTN_SE_CD IN ('M','F')
 ORDER BY POPLTN_CNT_SUM DESC 
;
--SQL Error [979] [42000]: ORA-00979: not a GROUP BY expression

--GROUP BY 절에 기재한 칼럼은 반드시 SELECT절에 기재하지 않아도 된다.
--8-21 GROUP BY 절 사용
SELECT POPLTN_SE_CD 
     , SUM(POPLTN_CNT) POPLTN_CNT_SUM
  FROM TB_POPLTN 
 GROUP BY POPLTN_SE_CD 
 ORDER BY POPLTN_SE_CD 
;
--8-22 GROUP BY 절에 기재한 칼럼을 SELECT절에 기재하지 않아도 정상 작동
SELECT SUM(POPLTN_CNT) POPLTN_CNT_SUM
  FROM TB_POPLTN 
 GROUP BY POPLTN_SE_CD 
 ORDER BY POPLTN_SE_CD 
;

--GROUP BY 절 이용 시 ORDER BY 절에는 반드시 GROUP BY 절에서 기재한 칼럼 혹은 표현식이 와야 한다.
--8-23 GROUP BY 절을 이용한 SQL문
SELECT POPLTN_SE_CD
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD 
 ORDER BY POPLTN_CNT_SUM
;

--8-24 GROUP BY 절을 이용한 SQL문 - 에러 발생
SELECT POPLTN_SE_CD
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD 
 ORDER BY POPLTN_CNT
;
--SQL Error [979] [42000]: ORA-00979: not a GROUP BY expression

--8-25 GROUP BY 절을 이용한 SQL문 - 에러 발생
SELECT POPLTN_SE_CD
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD 
 ORDER BY ADSTRD_CD 
;
--SQL Error [979] [42000]: ORA-00979: not a GROUP BY expression

--GROUP BY 절에 사용한 칼럼, 표현식, 표현식에 대한 칼럼 앨리어스가 ORDER BY절에 와야 정상적으로 실행됨
--8-26 GROUP BY 절을 이용한 SQL문 - 정상 실행
SELECT POPLTN_SE_CD
     , SUM(POPLTN_CNT) AS POPLTN_CNT_SUM
  FROM TB_POPLTN
 GROUP BY POPLTN_SE_CD 
 ORDER BY POPLTN_SE_CD, SUM(POPLTN_CNT), POPLTN_CNT_SUM 
;