--8.4 집합연산자
--UNION ALL 이용 시 ORDER BY절은 전체 결과집합을 정렬한다.
--8-33 UNION ALL을 이용한 SQL문
SELECT '2번째SELECT문' AS TEXT FROM DUAL 
UNION ALL
SELECT '1번째SELECT문' AS TEXT FROM DUAL
;

--8-34 UNION ALL + ORDER BY 절을 이용한 SQL문
SELECT '2번째SELECT문' AS TEXT FROM DUAL 
UNION ALL
SELECT '1번째SELECT문' AS TEXT FROM DUAL
ORDER BY TEXT
;

--집합연산자 이용 시 헤더명은 맨 위의 SELECT문을 따르고 ORDER BY 절은 맨 아래의 SELECT문을 따른다.
--8-35 UNION ALL 이용 시 헤더명 지정 및 ORDER BY 1 사용
SELECT A.SUBWAY_STATN_NO AS "지하철역번호"
     , A.LN_NM AS "노선명"
     , A.STATN_NM AS "역명"
 FROM TB_SUBWAY_STATN A WHERE STATN_NM = '강남'
UNION ALL 
SELECT B.SUBWAY_STATN_NO
     , B.LN_NM 
     , B.STATN_NM 
  FROM TB_SUBWAY_STATN B WHERE STATN_NM = '역삼'
UNION ALL 
SELECT C.SUBWAY_STATN_NO 
     , C.LN_NM 
     , C.STATN_NM 
  FROM TB_SUBWAY_STATN C WHERE STATN_NM = '선릉'
 ORDER BY 1 --컬럼 번호(1부터 시작)
;

--8-36 UNION ALL 이용 시 헤더명 지정 및 ORDER BY 절에 앨리어스 사용
SELECT A.SUBWAY_STATN_NO AS "지하철역번호"
     , A.LN_NM AS "노선명"
     , A.STATN_NM AS "역명"
 FROM TB_SUBWAY_STATN A WHERE STATN_NM = '강남'
UNION ALL 
SELECT B.SUBWAY_STATN_NO
     , B.LN_NM 
     , B.STATN_NM 
  FROM TB_SUBWAY_STATN B WHERE STATN_NM = '역삼'
UNION ALL 
SELECT C.SUBWAY_STATN_NO 
     , C.LN_NM 
     , C.STATN_NM 
  FROM TB_SUBWAY_STATN C WHERE STATN_NM = '선릉'
 ORDER BY "지하철역번호"
;
--SQL Error [904] [42000]: ORA-00904: "지하철역번호": invalid identifier

SELECT A.SUBWAY_STATN_NO AS "지하철역번호"
     , A.LN_NM AS "노선명"
     , A.STATN_NM AS "역명"
 FROM TB_SUBWAY_STATN A WHERE STATN_NM = '강남'
UNION ALL 
SELECT B.SUBWAY_STATN_NO
     , B.LN_NM 
     , B.STATN_NM 
  FROM TB_SUBWAY_STATN B WHERE STATN_NM = '역삼'
UNION ALL 
SELECT C.SUBWAY_STATN_NO 
     , C.LN_NM 
     , C.STATN_NM 
  FROM TB_SUBWAY_STATN C WHERE STATN_NM = '선릉'
 ORDER BY SUBWAY_STATN_NO 
;
--SQL Error [904] [42000]: ORA-00904: "SUBWAY_STATN_NO": invalid identifier

SELECT A.SUBWAY_STATN_NO
     , A.LN_NM AS "노선명"
     , A.STATN_NM AS "역명"
 FROM TB_SUBWAY_STATN A WHERE STATN_NM = '강남'
UNION ALL 
SELECT B.SUBWAY_STATN_NO
     , B.LN_NM 
     , B.STATN_NM 
  FROM TB_SUBWAY_STATN B WHERE STATN_NM = '역삼'
UNION ALL 
SELECT C.SUBWAY_STATN_NO 
     , C.LN_NM 
     , C.STATN_NM 
  FROM TB_SUBWAY_STATN C WHERE STATN_NM = '선릉'
 ORDER BY SUBWAY_STATN_NO 
;
--정상 실행

--MINUS 연산 시 집합의 결과는 중복이 제거된 행으로 출력된다.
--8-38 일반적인 SQL문
SELECT 
       A.STATN_NM
  FROM TB_SUBWAY_STATN A
 WHERE A.STATN_NM = '선릉'
;

--8-39 MINUS 연산 수행
SELECT A.STATN_NM 
  FROM TB_SUBWAY_STATN A WHERE A.STATN_NM = '선릉'
  MINUS 
  SELECT A.STATN_NM 
    FROM TB_SUBWAY_STATN A WHERE A.STATN_NM = '강남'
;