--8.6
--NATURAL JOIN 시 조인 칼럼에는 테이블 앨리어스를 쓸 수 없다.
--8-47 NATURAL JOIN을 이용한 SELECT문
SELECT ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT, B.ADSTRD_NM
  FROM TB_POPLTN A NATURAL JOIN TB_ADSTRD B 
 WHERE ADSTRD_CD = '4128157500' --경기도 고양시 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M', 'F')
   AND A.AGRDE_SE_CD IN ('000','010')
;

--8-48 NATURAL JOIN SQL문 - 문법 에러
SELECT A.ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT, B.ADSTRD_NM
  FROM TB_POPLTN A NATURAL JOIN TB_ADSTRD B 
 WHERE ADSTRD_CD = '4128157500' --경기도 고양시 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M', 'F')
   AND A.AGRDE_SE_CD IN ('000','010')
;
--SQL Error [25155] [99999]: ORA-25155: column used in NATURAL join cannot have qualifier


--INNER JOIN 시에는 동일한 칼럼이 있을 경우 테이블 앨리어스를 반드시 붙여야 한다.
--8-49 INNER JOIN SQL문
SELECT A.ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT, B.ADSTRD_NM
  FROM TB_POPLTN A INNER JOIN TB_ADSTRD B 
    ON (A.ADSTRD_CD = B.ADSTRD_CD)
 WHERE A.ADSTRD_CD = '4128157500' --경기도 고양식 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M','F')
   AND A.AGRDE_SE_CD IN ('000','010')
;

--8-50 INNER JOIN SQL문 - 에러 발생
SELECT A.ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT, B.ADSTRD_NM
  FROM TB_POPLTN A INNER JOIN TB_ADSTRD B 
    ON (ADSTRD_CD = ADSTRD_CD)
 WHERE A.ADSTRD_CD = '4128157500' --경기도 고양식 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M','F')
   AND A.AGRDE_SE_CD IN ('000','010')
;
--SQL Error [918] [42000]: ORA-00918: column ambiguously defined