--ON 절을 이용한 조인 시 조인 컬럼이 조인 대상 테이블에 존재하는 컬럼인 경우 반드시 테이블 앨리어스를 써야 한다.
--8-57 ON절 사용
SELECT A.ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT 
  FROM TB_POPLTN A INNER JOIN TB_ADSTRD B 
    ON (A.ADSTRD_CD = B.ADSTRD_CD)
 WHERE A.ADSTRD_CD = '4128157500' --경기도 고양시 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M','F')
   AND A.AGRDE_SE_CD IN ('000','010')
;

--8-58 ON절 사용 - 테이블 앨리어스 사용 안 함
SELECT A.ADSTRD_CD, A.STD_YM, A.POPLTN_SE_CD, A.AGRDE_SE_CD, A.POPLTN_CNT 
  FROM TB_POPLTN A INNER JOIN TB_ADSTRD B 
    ON (ADSTRD_CD = B.ADSTRD_CD)
 WHERE A.ADSTRD_CD = '4128157500' --경기도 고양시 덕양구 삼송동
   AND A.POPLTN_SE_CD IN ('M','F')
   AND A.AGRDE_SE_CD IN ('000','010')
;
--SQL Error [918] [42000]: ORA-00918: column ambiguously defined


--LEFT OUTER JOIN 기준으로 1:M 관계인 경우 LEFT OUTER JOIN의 결과집합의 내용은
--LEFT 기준이지만 결과집합의 건수는 RIGHT 기준이다.
--8-59 실습환경 구축
CREATE TABLE TB_CUST_8_6_6
(
  CUST_ID VARCHAR2(20)
, CUST_NM VARCHAR2(50)
, CONSTRAINT PK_TB_CUST_8_6_6 PRIMARY KEY(CUST_ID)
)
;

INSERT INTO TB_CUST_8_6_6 VALUES ('DBMSEXPERT', '이경오');
INSERT INTO TB_CUST_8_6_6 VALUES ('ORAEXPERT','최민수');

CREATE TABLE TB_ORD_8_6_6
(
  ORD_NO CHAR(10)
, ORD_AMT NUMBER(15)
, PRDT_CD CHAR(6)
, CUST_ID VARCHAR2(20)
, CONSTRAINT PK_TB_ORD_8_6_6 PRIMARY KEY(ORD_NO)
)
;

INSERT INTO TB_ORD_8_6_6 VALUES('1000000001',30000,'P00001','DBMSEXPERT');
INSERT INTO TB_ORD_8_6_6 VALUES('1000000002',60000,'P00001','DBMSEXPERT');


--8-60 LEFT OUTER JOIN 수행
SELECT A.CUST_ID
     , A.CUST_NM 
     , NVL(B.ORD_NO, '[NULL]') AS ORD_NO
     , NVL(B.ORD_AMT, 0) AS ORD_AMT
     , NVL(B.PRDT_CD, '[NULL]') AS PRDT_CD
     , NVL(B.CUST_ID, '[NULL]') AS CUST_ID
  FROM TB_CUST_8_6_6 A LEFT OUTER JOIN TB_ORD_8_6_6 B
    ON (A.CUST_ID = B.CUST_ID)
;
--'이경오'는 2건의 주문을 가지고 있기 때문에 2건이 출력
--'최민수'는 주문 내역이 존재하지 않지만, 고객으로는 존재하기 때문에 1건 출력